name: Python Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: pylint app/

    - name: Check code formatting with black
      run: black --check app/

    - name: Run flake8
      run: flake8 app/

    - name: Run mypy
      run: mypy app/

    - name: Run pytest
      run: pytest tests/
